apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - image: okteto.dev/node:18
          name: web
          command: ["npm", "run", "--prefix", "apps/web", "start"]

---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      name: "web"
      port: 8080
  selector:
    app: web

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web
  annotations:
    dev.okteto.com/generate-host: web
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: web
                port:
                  number: 8080
            path: /
            pathType: ImplementationSpecific
